# Shape Manipulation
An array has a shape given by the number of elements along each axis:

## Changing the shape of an array
Several arrays can be stacked together along different axes:

In [13]:
from numpy import *
a = floor(10*random.random((3,4)))
a

array([[ 9.,  2.,  0.,  6.],
       [ 8.,  9.,  5.,  5.],
       [ 5.,  5.,  2.,  2.]])

In [7]:
a.shape

(3, 4)

The shape of an array can be changed with various commands:

In [14]:
a.ravel() # flatten the array

array([ 9.,  2.,  0.,  6.,  8.,  9.,  5.,  5.,  5.,  5.,  2.,  2.])

In [18]:
a.shape = (6,2)
a

array([[ 9.,  2.],
       [ 0.,  6.],
       [ 8.,  9.],
       [ 5.,  5.],
       [ 5.,  5.],
       [ 2.,  2.]])

In [19]:
a.transpose()

array([[ 9.,  0.,  8.,  5.,  5.,  2.],
       [ 2.,  6.,  9.,  5.,  5.,  2.]])

The order of the elements in the array resulting from ravel() is normally "C-style", that is, the rightmost index "changes the fastest", so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as "C-style". Numpy normally creates arrays stored in this order, so ravel() will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.  
The reshape function returns its argument with a modified shape, whereas the resize method modifies the array itself:

In [20]:
a

array([[ 9.,  2.],
       [ 0.,  6.],
       [ 8.,  9.],
       [ 5.,  5.],
       [ 5.,  5.],
       [ 2.,  2.]])

In [23]:
a.resize(2,6)
a


array([[ 9.,  2.,  0.,  6.,  8.,  9.],
       [ 5.,  5.,  5.,  5.,  2.,  2.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [24]:
a.reshape(3,-1)

array([[ 9.,  2.,  0.,  6.],
       [ 8.,  9.,  5.,  5.],
       [ 5.,  5.,  2.,  2.]])

See also:: shape example, reshape example, resize example, ravel example

## Stacking together different 
Several arrays can be stacked together along different axes:

In [27]:
a = floor(10*random.random((2,2)))
a

array([[ 1.,  8.],
       [ 2.,  6.]])

In [29]:
b = floor(10*random.random((2,2)))
b

array([[ 5.,  9.],
       [ 4.,  2.]])

In [31]:
vstack((a,b))

array([[ 1.,  8.],
       [ 2.,  6.],
       [ 5.,  9.],
       [ 4.,  2.]])

In [32]:
hstack((a,b))

array([[ 1.,  8.,  5.,  9.],
       [ 2.,  6.,  4.,  2.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to vstack only for 1D arrays:

In [35]:
column_stack((a,b)) #with 2D arrays

array([[ 1.,  8.,  5.,  9.],
       [ 2.,  6.,  4.,  2.]])

In [37]:
 a=array([4.,2.])
 b=array([2.,8.])

In [38]:
a[:,newaxis]  # This allows to have a 2D columns vector

array([[ 4.],
       [ 2.]])

In [39]:
column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [40]:
vstack((a[:,newaxis],b[:,newaxis])) # The behavior of vstack is different

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

The function row_stack, on the other hand, stacks 1D arrays as rows into a 2D array.  
For arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

- Note  
In complex cases, r_[] and c_[] are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (":") :

In [41]:
r_[1:4,0,4]

array([1, 2, 3, 0, 4])

When used with arrays as arguments, r_[] and c_[] are similar to vstack and hstack in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate.  

See also: hstack example, vstack exammple, column_stack example, row_stack example, concatenate example, c_ example, r_ example

## Splitting one array into several smaller ones
Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [48]:
a = floor(10*random.random((2,12)))
a

array([[ 8.,  1.,  3.,  8.,  4.,  7.,  6.,  1.,  2.,  0.,  4.,  5.],
       [ 9.,  5.,  8.,  3.,  5.,  1.,  4.,  4.,  0.,  5.,  7.,  8.]])

In [49]:
hsplit(a,3)   # Split a into 3

[array([[ 8.,  1.,  3.,  8.],
        [ 9.,  5.,  8.,  3.]]), array([[ 4.,  7.,  6.,  1.],
        [ 5.,  1.,  4.,  4.]]), array([[ 2.,  0.,  4.,  5.],
        [ 0.,  5.,  7.,  8.]])]

In [50]:
hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[ 8.,  1.,  3.],
        [ 9.,  5.,  8.]]), array([[ 8.],
        [ 3.]]), array([[ 4.,  7.,  6.,  1.,  2.,  0.,  4.,  5.],
        [ 5.,  1.,  4.,  4.,  0.,  5.,  7.,  8.]])]

vsplit splits along the vertical axis, and array split allows one to specify along which axis to split.