#Copies and Views
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

## No Copy at All
Simple assignments make no copy of array objects or of their data.

In [4]:
from numpy import *
a = arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [6]:
b.shape = 3,4    # changes the shape of a 
a.shape
(3, 4)

(3, 4)

Python passes mutable objects as references, so function calls make no copy.

In [7]:
def f(x):
    print id(x)
id(a)

4459550160

In [8]:
f(a)

4459550160


## View or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.


In [10]:
c = a.view()
c is a

False

In [12]:
c.base is a                        # c is a view of the data owned by a

True

In [13]:
c.flags.owndata

False

In [15]:
c.shape = 2,6                      # a's shape doesn't change
a.shape

(3, 4)

In [17]:
c[0,4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:

In [19]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [23]:
s.base is a

True

## Deep Copy
The copy method makes a complete copy of the array and its data.


In [21]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [22]:
d.base is a                           # d doesn't share anything with a

False

In [25]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

##Functions and Methods Overview
Here is a list of NumPy functions and methods names ordered in some categories. The names link to the Numpy Example List so that you can see the functions in action.

- **Array Creation**  
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r , zeros, zeros_like


- **Conversions**  
astype, atleast 1d, atleast 2d, atleast 3d, mat


- **Manipulations**  
array split, column stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack


- **Questions**  
all, any, nonzero, where


- **Ordering**  
argmax, argmin, argsort, max, min, ptp, searchsorted, sort


- **Operations**  
choose, compress, cumprod, cumsum, inner, fill, imag, prod, put, putmask, real, sum


- **Basic Statistics**  
cov, mean, std, var


- **Basic Linear Algebra**  
cross, dot, outer, svd, vdot