# The Basics
NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.  
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.
```python
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
 ```
  Numpy's array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

- **ndarray.ndim**  
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

- **ndarray.shape**  
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

- **ndarray.size**  
the total number of elements of the array. This is equal to the product of the elements of shape.

- **ndarray.dtype**  
an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

- **ndarray.itemsize**  
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

- **ndarray.data**  
the buffer containing the actual elements of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.


## An example

In [2]:
from numpy  import *
a = arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [6]:
type(a)

numpy.ndarray

In [10]:
b = array([6, 7, 8])
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

##Array Creation
There are several ways to create arrays.  
For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [12]:
from numpy import *
a = array( [2,3,4] )
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [14]:
b = array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [16]:
 a = array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [17]:
a = array([1,2,3,4])  

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.


In [18]:
b = array( [ (1.5,2,3), (4,5,6) ] )
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

The type of the array can also be explicitly specified at creation time:

In [20]:
c = array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.  
The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [21]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [22]:
ones( (2,3,4), dtype=int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
empty( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists

In [25]:
arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [27]:
arange( 0, 2, 0.3 )                 # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:


In [28]:
linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [29]:
x = linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points

- **See also**  
array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, rand, randn, fromfunction, fromfile

## Printing Array
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.


In [32]:
a = arange(6)                         # 1d array
print a

[0 1 2 3 4 5]


In [34]:
b = arange(12).reshape(4,3)           # 2d array
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
c = arange(24).reshape(2,3,4)         # 3d array
print c

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


See below to get more details on reshape.  
If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:


In [35]:
print arange(10000)

[   0    1    2 ..., 9997 9998 9999]


In [37]:
print arange(10000).reshape(100,100)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
```python
set_printoptions(threshold='nan')
```

## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [38]:
a = array( [20,30,40,50] )
b = arange(4)
b

array([0, 1, 2, 3])

In [40]:
c = a - b
c

array([20, 29, 38, 47])

In [41]:
b ** 2

array([0, 1, 4, 9])

In [43]:
10 * sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [44]:
a<35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or creating matrix objects ( see matrix section of this tutorial ).

In [47]:
A = array(  [[1,1],
                    [0,1]])

In [48]:
B = array(  [[2,0],
                    [3,4]])

In [49]:
A*B

array([[2, 0],
       [0, 4]])

In [51]:
dot(A, B)

array([[5, 4],
       [3, 4]])

In [63]:
a = ones((2,3), dtype=int)
b = random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [64]:
b += a
b

array([[ 3.19426912,  3.99401789,  3.20273228],
       [ 3.9861647 ,  3.69622282,  3.5769479 ]])

In [67]:
a += b
a

array([[12, 12, 12],
       [12, 12, 12]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [73]:
a = ones(3, dtype=int32)
b = linspace(0, pi, 3)
b.dtype.name

'float64'

In [74]:
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [76]:
c.dtype.name

'float64'

In [78]:
d = exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [79]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [82]:
a = random.random((2,3))
a

array([[ 0.56712184,  0.06993586,  0.91071967],
       [ 0.58218899,  0.98383577,  0.22078955]])

In [84]:
a.sum()

3.3345916824365647

In [86]:
a.min()

0.069935860224935142

In [87]:
a.max()

0.98383577211787232

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [89]:
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [91]:
b.min(axis=1)

array([0, 4, 8])

In [92]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called "universal functions"(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.


In [95]:
B = arange(3)
B

array([0, 1, 2])

In [96]:
exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [97]:
sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [98]:
C = array([2., -1, 3.])
add(B,C)

array([ 2.,  0.,  5.])

- **See also**  
all, alltrue, any, apply along axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, conjugate, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sometrue, sort, std, sum, trace, transpose, var, vdot, vectorize, where


## Indexing, Slicing and Iterating
**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [103]:
a = arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [104]:
a[2]

8

In [106]:
a[2:5]

array([ 8, 27, 64])

In [112]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [114]:
a[ : :-1]                                 # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [117]:
for i in a:
    print i ** (1/3.),

nan 1.0 nan 3.0 nan 5.0 6.0 7.0 8.0 9.0


/Users/hyunho/.virtualenvs/py_visual/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: RuntimeWarning: invalid value encountered in power
  from IPython.kernel.zmq import kernelapp as app


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:


In [119]:
def f(x,y):
    return 10 * x + y
f(1, 2)

12

In [120]:
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [122]:
b[2,3]

23

In [131]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [130]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [128]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [127]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].
The **dots** (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 array (i.e., it has 5 axes), then
- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].

In [134]:
c = array( [ [[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],

              [[100,101,102],
               [110,112,113]] ] )
c.shape

(2, 2, 3)

In [135]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [136]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

**Iterating** over multidimensional arrays is done with respect to the first axis:

In [138]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [137]:
for row in b:
    print row

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [139]:
for element in b.flat:
    print element,

0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43


- **See also**  
[], ..., newaxis, ndenumerate, indices, index exp